server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Serve the generated JSON from the Docker shared volume
    location = /dashboard_data.json {
        alias /app/shared/dashboard_data.json;
        add_header Cache-Control "no-store";
    }
}
